fix: set the correct fallback for Snippet completion
atom-community/atom-languageclient pull request #148
Opened 2021-04-20 22:46 UTC by ayame113

Currently, Snippets without `insertText` are not completed (empty strings are inserted).
According to the lsp `CompletionItem` spec, Implementation should fall back to `label`.
This pull request fixes it.

>https://microsoft.github.io/language-server-protocol/specification#textDocument_completion
>A string that should be inserted into a document when selecting this completion. When `falsy` the label is used as the insert text for this item.

2021-04-20 23:31 UTC, UziTech requested changes
Thanks! Could you add a test?

2021-04-21 00:45 UTC, ayame113 commented
Thank you for review.
Added a test. However, I'm new to writing tests so I don't know if this is correct ...

2021-04-21 02:33 UTC, UziTech approved these changes

2021-04-21 02:38 UTC, merged

2021-04-21 02:43 UTC, UziTech commented
Looks great! :100: Thanks for the PR!

2021-04-21 04:06 UTC, ayame113 commented
Thank you!