feat: make the languageId of didOpen notifications configurable
atom-community/atom-languageclient pull request #179
Opened 2021-07-27 07:16 UTC by ayame113

PR for https://github.com/atom-community/atom-languageclient/issues/178.

2021-07-27 07:22 UTC, ayame113 commented on lib/adapters/document-sync-adapter.ts
>      private _versions: Map<string, number>,
There are minor changes to enable JSDoc that are unrelated to the issue.

2021-07-27 14:29 UTC, UziTech approved these changes
Nice work! :100:

2021-07-30 22:53 UTC, aminya requested changes

2021-07-30 22:53 UTC, aminya commented on lib/auto-languageclient.ts
> +  public getLanguageIdFromEditor(_editor: TextEditor): string | void | null {}
I would prefer to have a working function and use it as it is. The client can override a custom behaviour if they want to.

```suggestion
  protected getLanguageIdFromEditor(_editor: TextEditor): string | void | null {
    return this._editor.getGrammar().name
  }
```

2021-07-30 22:54 UTC, aminya commented on lib/adapters/document-sync-adapter.ts
> +    return this._getLanguageIdFromEditor(this._editor) ?? this._editor.getGrammar().name
```suggestion
    return this._getLanguageIdFromEditor(this._editor)
```

2021-07-31 10:44 UTC, ayame113 commented
Thank you for your review!

@aminya 
I fixed it as mentioned in the comment.

2021-07-31 21:54 UTC, aminya approved these changes
Thanks for your contribution!

2021-07-31 21:54 UTC, merged